apiVersion: v2
name: n8n
description: A Helm chart for deploying n8n workflow automation on Kubernetes
type: application
version: 0.0.0  # set from git tag at release time
appVersion: "2.6.4"

home: https://github.com/ATHEO-Ingenierie/n8n-helm
sources:
  - https://github.com/ATHEO-Ingenierie/n8n-helm
annotations:
  org.opencontainers.image.source: https://github.com/ATHEO-Ingenierie/n8n-helm
  org.opencontainers.image.description: A Helm chart for deploying n8n workflow automation on Kubernetes
