{{- $needsDbPassword := and (eq .Values.database.type "postgresdb") (not (empty .Values.database.postgresdb.password)) (empty .Values.database.postgresdb.existingSecret) -}}
{{- $needsRedisPassword := and (not (empty .Values.externalRedis.password)) (empty .Values.externalRedis.existingSecret) -}}
{{- $needsRunnerToken := and (eq .Values.runners.mode "external") (not (empty .Values.runners.authToken)) -}}
{{- $needsS3Credentials := and .Values.externalS3.enabled (not (empty .Values.externalS3.accessKey)) (empty .Values.externalS3.existingSecret) -}}
{{- if or $needsDbPassword $needsRedisPassword $needsRunnerToken $needsS3Credentials }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "n8n.fullname" . }}-credentials
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if $needsDbPassword }}
  db-password: {{ .Values.database.postgresdb.password | quote }}
  {{- end }}
  {{- if $needsRedisPassword }}
  redis-password: {{ .Values.externalRedis.password | quote }}
  {{- end }}
  {{- if $needsRunnerToken }}
  runner-auth-token: {{ .Values.runners.authToken | quote }}
  {{- end }}
  {{- if $needsS3Credentials }}
  s3-access-key: {{ .Values.externalS3.accessKey | quote }}
  s3-access-secret: {{ .Values.externalS3.accessSecret | quote }}
  {{- end }}
{{- end }}
