{{- $needsUserSecret := not (empty .Values.secret) -}}
{{- if $needsUserSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "n8n.fullname" . }}
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secret }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
